[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "twit"
version = "0.1.0"
description = "A toy version control system from scratch"
dependencies = []

[project.scripts]
twit = "twit.cli:main"